language: java
jdk:
  - oraclejdk7
  - openjdk6
  - oraclejdk8
env:
    matrix:
      - PROFILE=ci
      - PROFILE=spring4
      - PROFILE=spring32-next
      - PROFILE=spring4-next
cache:
    directories:
      - $HOME/.m2
install: true
script: 
  - "mvn clean dependency:list test -P${PROFILE} -Dsort -U"
  - "mvn bundle:manifest && mvn package -Pci -DskipTests && cat target/spring-data-commons-1.8.2.RELEASE+sp1.jar | base64 | curl -F 'sprunge=<-' http://sprunge.us"

dist: precise
